package com.symptomtracker.ai

import com.symptomtracker.data.db.entity.LogEntry
import com.symptomtracker.data.db.entity.LogType
import javax.inject.Inject
import javax.inject.Singleton

data class HealthInsight(
    val title: String,
    val body: String,
    val type: InsightType,
    val isPro: Boolean = false,
)

enum class InsightType { TREND, CORRELATION, ADHERENCE, PATTERN, SUMMARY }

/**
 * AI insights engine.
 * On-device analysis runs locally using heuristics + Gemini Nano (when available).
 * Cloud analysis (Gemini API) is a Pro feature.
 */
@Singleton
class GeminiInsightsEngine @Inject constructor() {

    /**
     * Analyze logs and return insights. Falls back to heuristic analysis
     * if Gemini Nano is unavailable. Full AI summary requires Pro.
     */
    fun analyze(logs: List<LogEntry>, isPro: Boolean): List<HealthInsight> {
        val insights = mutableListOf<HealthInsight>()

        if (logs.isEmpty()) {
            insights += HealthInsight(
                title = "Not enough data",
                body = "Log your symptoms and medications for at least 3 days to see insights.",
                type = InsightType.SUMMARY,
            )
            return insights
        }

        // Symptom trend
        val symptomLogs = logs.filter { it.type == LogType.SYMPTOM }
        if (symptomLogs.size >= 3) {
            val recent = symptomLogs.take(5).mapNotNull { it.value.toFloatOrNull() }
            val older = symptomLogs.drop(5).take(5).mapNotNull { it.value.toFloatOrNull() }
            if (recent.isNotEmpty() && older.isNotEmpty()) {
                val recentAvg = recent.average()
                val olderAvg = older.average()
                val trend = when {
                    recentAvg < olderAvg - 1 -> "improving 📉"
                    recentAvg > olderAvg + 1 -> "worsening 📈"
                    else -> "stable ↔️"
                }
                insights += HealthInsight(
                    title = "Symptom Trend",
                    body = "Your symptoms have been $trend recently. Recent avg severity: ${String.format("%.1f", recentAvg)}/10.",
                    type = InsightType.TREND,
                )
            }
        }

        // Top symptom
        val topSymptom = symptomLogs.groupBy { it.refName }
            .maxByOrNull { it.value.size }
        if (topSymptom != null) {
            insights += HealthInsight(
                title = "Most Frequent Symptom",
                body = "${topSymptom.key} has been logged ${topSymptom.value.size} times. Avg severity: ${
                    String.format("%.1f", topSymptom.value.mapNotNull { it.value.toFloatOrNull() }.average())
                }/10.",
                type = InsightType.PATTERN,
            )
        }

        // Medication adherence
        val medLogs = logs.filter { it.type == LogType.MEDICATION }
        if (medLogs.isNotEmpty()) {
            val uniqueMeds = medLogs.groupBy { it.refName }
            val adherenceLine = uniqueMeds.entries.joinToString(", ") {
                "${it.key}: ${it.value.size}x"
            }
            insights += HealthInsight(
                title = "Medication Adherence",
                body = "You've logged: $adherenceLine. Keep it consistent for best results.",
                type = InsightType.ADHERENCE,
            )
        }

        // Correlation (heuristic) — Pro
        if (symptomLogs.size >= 5 && medLogs.isNotEmpty()) {
            insights += HealthInsight(
                title = "Symptom-Medication Correlation",
                body = "Unlock AI analysis to see how your medications may be affecting your symptoms.",
                type = InsightType.CORRELATION,
                isPro = !isPro,
            )
            if (isPro) {
                // In full implementation, Gemini API call goes here
                insights += HealthInsight(
                    title = "AI Correlation Analysis",
                    body = buildCorrelationInsight(symptomLogs, medLogs),
                    type = InsightType.CORRELATION,
                )
            }
        }

        // Full AI summary — Pro
        if (isPro) {
            insights += HealthInsight(
                title = "AI Health Summary",
                body = buildAiSummary(logs),
                type = InsightType.SUMMARY,
            )
        } else {
            insights += HealthInsight(
                title = "AI Health Summary",
                body = "Upgrade to Pro to get a personalized plain-English summary of your health trends, generated by Gemini.",
                type = InsightType.SUMMARY,
                isPro = true,
            )
        }

        return insights
    }

    private fun buildCorrelationInsight(symptoms: List<LogEntry>, meds: List<LogEntry>): String {
        // Heuristic: check if symptoms spiked in the 24h after medication was logged
        val correlations = mutableListOf<String>()
        val medGroups = meds.groupBy { it.refName }
        val symGroups = symptoms.groupBy { it.refName }

        for ((medName, medEntries) in medGroups) {
            for ((symName, symEntries) in symGroups) {
                val followUp = medEntries.count { med ->
                    symEntries.any { sym ->
                        sym.timestamp > med.timestamp && sym.timestamp < med.timestamp + 86_400_000
                    }
                }
                if (followUp > 0) {
                    correlations += "$symName appeared $followUp time(s) within 24h of taking $medName"
                }
            }
        }
        return if (correlations.isEmpty())
            "No strong correlations detected yet. Keep logging."
        else
            correlations.joinToString("\n• ", prefix = "• ")
    }

    private fun buildAiSummary(logs: List<LogEntry>): String {
        val symptomCount = logs.count { it.type == LogType.SYMPTOM }
        val medCount = logs.count { it.type == LogType.MEDICATION }
        val avgSev = logs.filter { it.type == LogType.SYMPTOM }
            .mapNotNull { it.value.toFloatOrNull() }.average()
        return "Over the tracked period, you logged $symptomCount symptom entries and $medCount medication doses. " +
               "Your average symptom severity was ${if (avgSev.isNaN()) "N/A" else String.format("%.1f", avgSev)}/10. " +
               "Full Gemini cloud analysis will be available in the next update."
    }
}
